version: "3.7"

services:
  web:
    build:
      dockerfile: docker/Dockerfile
    restart: always
    ports:
     - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data

