# Generated by Django 4.1.6 on 2023-02-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="name",
            field=models.CharField(default="some name", max_length=63),
            preserve_default=False,
        ),
    ]
