# Generated by Django 4.1.6 on 2023-02-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_order_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="description",
            field=models.TextField(default="SOME DESC"),
            preserve_default=False,
        ),
    ]
